config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  
  resources :facilities do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
  
  get '/bookings', to: 'bookings#list'
  delete '/bookings/:id', to: 'bookings#delete', as: 'bookings_delete'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :facility
  validates :facility, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/facility.rb
class Facility < ApplicationRecord
  belongs_to :user
  has_many :reviews
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["Football", "Tennis", "Swimming pool", "Event"] }
  validates :description, presence: true
  validates :name, presence: true
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :facility
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :facilities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def list
    @bookings = Booking.all
  end

  def new
    @facility = Facility.find(params[:facility_id])
    @booking = Booking.new
  end

  def create
    @facility = Facility.find(params[:facility_id])
    @booking = Booking.new(booking_params)
    @booking.facility = @facility
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path, notice: "Your booking has been successfully created"
    else
      render :new
    end
  end

  def delete
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

    private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  def index


    if params[:query].present?
      sql_query = "category ILIKE :query"
      @facilities = Facility.where(sql_query, query: "%#{params[:query]}%")
    else
      @facilities = Facility.geocoded
      @facilities = Facility.order(created_at: :DESC)
    end

    @markers = @facilities.map do |facility|
      {
        lat: facility.latitude,
        lng: facility.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { facility: facility })
      }
    end


  end

  def show
    @facility = Facility.geocoded.find(params[:id])
    @reviews = @facility.reviews.order(updated_at: :desc).take(5)
    @markers = [{
        lat: @facility.latitude,
        lng: @facility.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { facility: @facility })
      }]
  end

  def new
    @facility = Facility.new
  end

  def create
    @facility = Facility.new(facility_params)
    @facility.user = current_user

    if @facility.save
      redirect_to @facility, notice: "Your facility has been successfully created"
    else
      render 'new'
    end

  end

  def edit
    @facility = Facility.find(params[:id])
  end

  def update
    @facility = Facility.find(params[:id])
    @facility.update(facility_params)
    redirect_to facility_path(@facility)
  end

  def destroy
    @facility = Facility.find(params[:id])
    @facility.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to facilities_path
  end

  def facility_params
    params.require(:facility).permit(:user_id, :name, :address, :category, :description, :price, :capacity, :photo)
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_facility, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.facility = @facility
    if @review.save
      redirect_to facility_path(@facility)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:facility_id, :content, :rating)
  end

  def set_facility
    @facility = Facility.find(params[:facility_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([@facility, @booking]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit  class: "submit-btn btn btn-primary" %>
  </div>
<% end %>

app/views/bookings/list.html.erb
  <div class ="fixed booking-background">
    <div class="container container-fluid content booking">
     <% if @bookings.blank? %>
       <p id="no-booking-yet"> No bookings yet ...</p>
     <% else %>
      <div class="whiteback">

        <div class="cards row mx-0">          
          <div class="col-12">
              <div class="row mx-2">
                <% @bookings.each do |booking| %>
                  <div class="card-trip col-12 px-0 mr-3 mb-2">
                      <% if booking.facility.photo.attached? %>
                      <%= cl_image_tag booking.facility.photo.key, crop: :fill, class:"img-index"%>
                    <% end %>

                  <div class="card-trip-infos">
                      <div>
                        <h2 class="card-title"><%= link_to booking.facility.name, bookings_path, class:"h5-card" %> Status: ✅</h2>
                        <p class="card-text"><%= booking.facility.address %></p>
                        <p><%= link_to "Cancel Booking", bookings_delete_path(booking), method: :delete,
                        data: { confirm: "Are you sure?" } %></p>
                      </div>
                      <h2 class="card-trip-pricing"> <%= booking.start_date.to_formatted_s(:rfc822) %> / <%= booking.end_date.to_formatted_s(:rfc822) %></h2>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/bookings/new.html.erb
<%= render "form" %>

app/views/facilities/_form.html.erb
<%= simple_form_for(@facility) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :category,collection: ["Football", "Tennis", "Swimming pool", "Event"] %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.submit  class: "submit-btn btn btn-primary" %>
  </div>
<% end %>

app/views/facilities/_info_window.html.erb
<h2 class ="h2-pop-up"><%= facility.name %></h2>
<p><%= facility.address %></p>
<strong><p class= "h2-pop-up"><%= facility.price %>€</p></strong>

app/views/facilities/create.html.erb
<h1>Facilities#create</h1>
<p>Find me in app/views/facilities/create.html.erb</p>

app/views/facilities/edit.html.erb
<%= render "form" %>

app/views/facilities/index.html.erb
<%= form_tag facilities_path, method: :get, class:"mx-3" do %>
  <%= select_tag :query,
    raw('<option value="Football">Football</option><option value="Tennis">Tennis</option><option value="Swimming pool">Swimming pool</option><option value="Event">Event</option>'),
    class: "form-control my-2",
    :include_blank => "All categories"
  %>
  <%= submit_tag "Search", class: "btn btn-flat" %>
<% end %>

<div class="container-fluid content">
  <div class="cards row mx-0">
    <div class="col-7">
      <div class="row mx-2">
    <% @facilities.each do |facility| %>
      <%= link_to facility, class:"card-index-link" do %>
        <div class="card-trip col-12 px-0 mr-3 mb-2">
          <% if facility.photo.attached? %>
          <%= cl_image_tag facility.photo.key, crop: :fill, class:"img-index"%>
      <% end %> 
    <%end%>
        <div class="card-trip-infos">
            <div>
              <h2 class="card-title"><%= link_to facility.name, facility_path(facility), class:"h5-card" %></h2>
              <p class="card-text"><%= facility.address %></p>
            </div>
            <h2 class="card-trip-pricing"><%= facility.price %> €</h2>
          </div>
        </div>
    <% end %>
  </div>
</div>

    <div class="col-md-5 map-container m-0 p-0">

      <div id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/facilities/new.html.erb
<div class="container forms-layout">

  <div class="form-inputs">
  <h1 class="form-title">Create a facility</h1>
  
  <%= simple_form_for( @facility) do |f| %>
    <%= f.input :name %>
    <%= f.input :address, id:"facility_address" %>
    <%= f.input :category, collection: ["Football", "Tennis", "Swimming pool", "Event"]%>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :capacity %>
    <%= f.input :photo, as: :file %>
    <%= f.submit  class: "submit-btn btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/facilities/show.html.erb
<%if @facility.category == "Tennis" %>

    <div class= "container-fluid show-G-container"  style="background-image: url(https://images.unsplash.com/photo-1554068865-24cecd4e34b8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80 ); background-repeat: no-repeat; background-size: cover">

      <%= render 'shared/facility_show' %>

    </div>


  <% elsif @facility.category == "Football" %>

    <div class= "container-fluid show-G-container"  style="background-image: url(https://images.unsplash.com/photo-1575361204480-aadea25e6e68?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1351&q=80 ); background-repeat: no-repeat; background-size: cover">

      <%= render 'shared/facility_show' %>

    </div>

  <% elsif @facility.category == "Swimming pool" %>

    <div class= "container-fluid show-G-container"  style="background-image: url(https://images.unsplash.com/photo-1558617320-e695f0d420de?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80 ); background-repeat: no-repeat; background-size: cover">

      <%= render 'shared/facility_show' %>

    </div>



  <% elsif @facility.category == "Event" %>

    <div class= "container-fluid show-G-container"  style="background-image: url(https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80 ); background-repeat: no-repeat; background-size: cover">

      <%= render 'shared/facility_show' %>


    </div>


<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Athletiq</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;900&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <div class ="container-fluid px-0">
        <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1563299796-b729d0af54a5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1225&q=80)">
  <div class="container">
    <h1><strong>Athletiq</strong></h1>
    <div class="banner-underline"></div>
    <p>Rent your sport facilities easily ...</p>
    <%= link_to "Book a facility", facilities_path, class:"btn btn-flat"%>
    
  </div>
</div>

app/views/reviews/new.html.erb
<div class="form-inputs">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <%= simple_form_for [@facility, @review] do |f| %>
          <%= f.input :content, label: "Comment your experience" %>
          <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
          <%= f.submit class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_facility_show.erb
<div class="container">

  <div class="row">
      <div class="col-lg-8">
      <% if @facility.photo.attached? %>
          <%= cl_image_tag @facility.photo.key, width: 730 , height: 500, crop: :fill, class: "photo" %>
        <%end%>
      </div>
      <div class="card-product col-lg-4">
        <div class="card-product-infos fixed-card mr-4">
          <h2 class="h2show"><%=@facility.name%></h2>
          <p><strong>Category: </strong><%= @facility.category %></p>
          <p><strong>Address: </strong><%= @facility.address %></p>
          <p><strong>Capacity: </strong><%= @facility.capacity %></p>
          <p><strong>Description: </strong><%= @facility.description %></p>
          <p><strong>Price: </strong><%= @facility.price %><strong> €</strong></p>
          <div class="container container-button">
          <br><%= link_to "Book Now", new_facility_booking_path(@facility), class: "btn btn-flat" %>
          <%= link_to "Edit Facility", edit_facility_path, class: "btn btn-flat" %>
          <p><br></p> <%= link_to "Delete Facility", facility_path(@facility), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-flat"  %>
          <%= link_to "Submit review", new_facility_review_path(@facility), class: "btn btn-flat" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row" id="review-content">
      <% if @reviews.blank? %>
        Be the first to leave a review for <strong id="facname"> <%= @facility.name %> </strong>
      <% else %>
        <% @reviews.each do |review|%>
        <div class="col-9" id="comment">
          <p><i class="fas fa-comments"></i> <span id="spanreview"><%= review.content %></span> </p>
        </div>
        <br>
        <div class="col-3" id="star">
          <% if review.rating == 1 %>
            <p>⭐️</p>
            <% elsif review.rating == 2 %>
            <p>⭐️⭐️</p>
            <% elsif review.rating == 3 %>
            <p>⭐️⭐️⭐️</p>
            <% elsif review.rating == 4 %>
            <p>⭐️⭐️⭐️⭐️ </p>
            <% else review.rating == 5 %>
            <p>⭐️⭐️⭐️⭐️⭐️ </p>
          <%end%>
        </div>
        <%end%>
      <% end %>
    </div>

  <div class="row">
      <div class="col-lg-8">
      <div class="container-map">
      <div id="map"
                      style="width: 800px; height: 400px;"
                      data-markers="<%= @markers.to_json %>"
                      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
                    </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to "/", class: "navbar-brand" do %>
    <h1 class="nav-header"><strong>Athletiq<i class="fas fa-running"></i></strong></h1>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Facilities", facilities_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bookings", "/bookings", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Publish a facility", new_facility_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>